package domain.evento.valueobject;

public enum MotivoAlertaAlocacao {
    CUSTO_ACIMA_DO_TETO,
    CAPACIDADE_INSUFICIENTE,
    CONFLITO_AGENDA,
    INDISPONIBILIDADE_OU_BLOQUEIO,
    MANUTENCAO,
    RESERVA_EXISTENTE,
    INFRAESTRUTURA_INSUFICIENTE,
    LOCAL_INATIVO,
    PRINCIPAL_NAO_LOCALIZADO
}
